---
title: Terrain
author: John
date: '2020-04-07'
draft: false
categories:
  - GL
tags:
  - GL
  - Svelte
  - SvelteGL
  - WebGL
---

<div style="width: 100%; width: 1280px; min-width: 640px;">
<main id="gl-app" role="main"></main>
&nbsp;
</div>

## Terrain

```{r setup, echo=FALSE, include=FALSE}
options(warn = -1)
working_dir <- getwd()
print(working_dir)
if (!require("knitr")) {
    install.packages("knitr")
    library("knitr")
}
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(echo = TRUE)

# Load reticulate package for running python
if (!require("png")) {
    install.packages("png")
}
library(png)
```

If the output target is HTML, R has some methods for turning R data:
```{r data, echo = FALSE}
options(warn = -1)
working_dir <- getwd()
# print(working_dir)
heightmap <- data.frame(c())
if (print(file.exists("data/heightmap-small.png"))) {
    heightmap <- data.frame(png::readPNG("data/heightmap-small.png"))
    head(heightmap)
    # length(heightmap)
    # str(heightmap)
}
```

... into JavaScript or JSON data and printing the results within HTML tags:
```{r data_in_html, results='asis'}
require(jsonlite)

# print without tabs so R markdown will add it to the DOM tree of the resulting page
cat(paste('<div id="data_in_html"><script type="application/json">', toJSON(heightmap), '\n</script>\n</div>', sep=""))
```
